dependencies {
    implementation project(':model')
    implementation 'org.reactivecommons:async-kafka-starter:7.2.1'
    implementation 'tools.jackson.core:jackson-databind'
    implementation 'org.springframework:spring-context'
    implementation 'org.springframework.boot:spring-boot-starter'
}
